
dist: xenial
services:
  - postgresql
addons:
  postgresql: "9.4" "9.6"
env:
  -DB=postgres

before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
language: python
python:
- '3.6'
- '3.8'
install:
  - pip install -r requirements.txt
jobs:
  include:
    - script:
      - cd decide
      - run --branch --source=. ./manage.py test authentication/ --keepdb --with-xunit

    - script:
      - cd decide
      - run --branch --source=. ./manage.py test census/ --keepdb --with-xunit
